//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SettingsManagement.rc
//
#define IDD_PROPPAGE_CURVE              106
#define IDD_PROPPAGE_MEDIUM             306
#define IDD_PROPPAGE_LANGUAGE           306
#define IDD_PROPPAGE_PROMPT             307
#define IDD_PROPPAGE_EXPORT             308
#define IDD_PROPPAGE_DENSITO            309
#define IDC_LANG_COMBO                  1200
#define IDC_RADIO_SETTING_SIMPLE        1202
#define IDC_RADIO_SETTING_SMART         1203
#define IDC_EDIT_SETTING_THICKWIDTH     1204
#define IDC_BUTTON_SETTING_BLACKCOLOR   1205
#define IDC_RADIO_SETTING_TOPFOLLOW     1206
#define IDC_RADIO_SETTING_BOTTOMFOLLOW  1207
#define IDC_RADIO_SETTING_DASHED        1208
#define IDC_RADIO_SETTING_NOT_DASHED    1209
#define IDC_EDIT_SETTING_DASHMAX        1210
#define IDC_SPIN1                       1212
#define IDC_SPIN_DASHMAX                1212
#define IDC_BUTTON_SETTING_CURVEDEFAULTS 1213
#define IDC_SPIN_THICKRANGE             1214
#define IDC_RADIO_START_OPENGRAPHIC     1220
#define IDC_RADIO_START_IMPORTSCANNER   1221
#define IDC_RADIO_START_NONE            1222
#define IDC_RADIO_EXPORT_AUTOPROMPT     1223
#define IDC_RADIO_EXPORT_NOPROMPT       1224
#define IDC_RADIO_SETT_SEP_TAB          1225
#define IDC_RADIO_SETT_SEP_SEMIC        1226
#define IDC_RADIO_SETT_SEP_COMMA        1227
#define IDC_RADIO_SETT_SEP_SPACE        1228
#define IDC_RADIO_SETT_SEP_OTHER        1229
#define IDC_EDIT_SETT_SEP_OTHER         1230
#define IDC_EDIT_SETT_FILEEXTENSION     1231
#define IDC_SETTINGS_TOPCOLOR           1232
#define IDC_SETTINGS_BOTTOMCOLOR        1233
#define IDC_SETTINGS_COLORSCALE         1234
#define IDC_SETTINGS_TOPVALUE           1235
#define IDC_SETTINGS_BOTTOMVALUE        1236
#define IDS_ENGLISHLABEL                61301
#define IDS_FRENCHLABEL                 61302
#define IDS_SETT_SEPARATOR_ISEMPTY      61303
#define IDS_SETT_EXTENSION_ISEMPTY      61304
#define IDS_SETT_ALPHANUMERIC_EXTENSION 61305
#define IDS_SETT_MUST_GIVE_VALUE             61306
#define IDS_SETT_SCALE_VALUE_MUST_BE_DIFFERENT 61307
#define IDS_SETT_SCALE_COLOR_MUST_BE_DIFFERENT 61308

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        304
#define _APS_NEXT_COMMAND_VALUE         40201
#define _APS_NEXT_CONTROL_VALUE         1237
#define _APS_NEXT_SYMED_VALUE           302
#endif
#endif
