//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CurveUnscan.rc
//
#define IDD_ABOUTBOX                    100
#define WM_START_PICK                   101
#define WM_MOVE_PICK                    102
#define WM_END_PICK                     103
#define ID_SCROLL_TIMER                 104
#define IDC_PICK_COLOR_POINTER          104
#define WM_SCROLL_ON                    105
#define WM_SCROLL_OFF                   106
#define WM_ZOOM_CHANGES                 107
#define ID_MODIFICATION_DELAY_TIMER     108
#define WM_OPTDLG_CLOSED                109
#define WM_APPLY_DASHDIST               110
#define WM_DASHDISTDLG_CLOSED           111
#define WM_IMAGE_SCANNED                112
#define WM_SCANNER_CLOSED               113
#define WM_PREVIEWCLOSED                114
#define IDR_MAINFRAME                   128
#define IDR_UNSCANTYPE                  129
#define IDR_MAINFRAME_OLD               129
#define IDD_XSCALE_DIALOG               130
#define IDD_XDRAW_DIALOG                131
#define IDD_ROTATION_DIALOG             132
#define IDD_YDRAW_DIALOG                133
#define IDD_YSCALE_DIALOG               134
#define IDD_CURVEKIND_DIALOG            135
#define IDD_CURVELIMITS_DIALOG          136
#define IDD_THICKNESS_DIALOG            137
#define IDD_DISCRETE_DIALOG             138
#define IDD_CONTINUOUS_DIALOG           141
#define IDD_COMMON_DIALOG               143
#define IDD_HAND_DIALOG                 144
#define IDD_PERIOD_DIALOG               145
#define IDD_SAVE_DIALOG                 146
#define IDD_PREVIEW_DIALOG              149
#define IDD__TEST_DIALOG                150
#define IDD_ZOOM_DIALOG                 155
#define IDD_SAVETREE_DIALOG             159
#define IDI_UNDOICON                    162
#define IDI_REDOICON                    163
#define IDD_CONTINUOUSOPTION_DIALOG     164
#define IDB_BITMAP_PEN                  165
#define IDB_BITMAP_RUBBER               166
#define IDD_ASKTOSAVE_DIALOG            167
#define IDB_CONTINUOUS                  168
#define IDB_DISCRET                     169
#define IDR_CONTEXT_MENU                170
#define IDD_AXE_X                       171
#define IDD_AXE_Y                       172
#define IDD_DASHDIST_DIALOG             173
#define IDD_SCANNER                     177
#define IDD_SAVE_PROMPT                 178
#define IDD_EXPORT_FORMAT_DIALOG        179
#define IDD_DENSITO_DIALOG              180
#define IDI_DROPPER_ICON                181
#define IDC_MANUALDRAW_CURSOR           183
#define IDC_RUBBER_CURSOR               184
#define IDD_DENSITO_PERIOD_DIALOG       185
#define IDB_DENSITO                     186
#define IDD_SPLINE_DIALOG               187
#define IDI_SPLINE_ADD_BACK             188
#define IDI_SPLINE_ADD_FRONT            189
#define IDI_SPLINE_ADD_MIDDLE           190
#define IDI_SPLINE_REMOVE               191
#define IDI_SPLINE_MODIFY               192
#define IDD_SPLINE_PERIOD_DIALOG        193
#define IDB_SPLINE                      194
#define IDC_SORT                        1000
#define IDC_ADD_BUTTON                  1001
#define IDC_DELETE                      1002
#define IDC_REMOVE_BUTTON               1003
#define IDC_EDIT_THICK                  1004
#define IDS_CURVE                       1004
#define IDC_EDIT_LEGEND_PERIOD          1005
#define IDC_EDIT_LEGEND_FREQUENCY       1006
#define IDC_CHECK_ELEMENT               1007
#define IDC_EDIT_LEGEND_FIRSTVALUE      1008
#define IDC_RADIO_YES                   1009
#define IDC_RADIO_TOP                   1010
#define IDC_RADIO_NO                    1011
#define IDC_RADIO_BOTTOM                1012
#define IDC_EDIT1                       1013
#define IDC_EDIT_XNAME                  1014
#define IDC_EDIT_BOTTOM_COLOR_VALUE     1014
#define IDC_EDIT_XMIN                   1014
#define IDC_EDIT_GRAPHNAME              1015
#define IDC_EDIT_XMAX                   1015
#define IDC_EDIT_CURVENAME              1016
#define IDC_EDIT_XPERIOD                1016
#define IDC_EDIT_PERIOD                 1017
#define IDC_EDIT_XFREQ                  1017
#define IDC_PREVIEW_EDIT                1018
#define IDC_EDIT_XUNIT                  1018
#define IDC_EDIT_RIGHTVALUE             1019
#define IDC_EDIT_YMIN                   1019
#define IDC_EDIT_FREQUENCY              1020
#define IDC_EDIT_YMAX                   1020
#define IDC_CHECK_THICKNESS             1021
#define IDC_EDIT_YPERIOD                1021
#define IDC_CHECK_THICK                 1022
#define IDC_EDIT_YFREQ                  1022
#define IDC_EDIT_1STVALUE               1023
#define IDC_EDIT_YUNIT                  1023
#define IDC_CHECK_1ST                   1024
#define IDC_EDIT_2NDVALUE               1025
#define IDC_CHECK_2ND                   1026
#define IDC_RADIO_LINEAR                1027
#define IDC_RADIO_LOG                   1028
#define IDC_PREVIOUS                    1029
#define IDC_RADIO_CONTINUOUS            1030
#define IDC_RADIO_DISCRETE              1031
#define IDC_EDIT_LEFTVALUE              1032
#define IDC_CHECK_LEFT                  1033
#define IDC_CHECK_RIGHT                 1034
#define IDC_EDIT_ANGLE                  1035
#define IDC_LIST_POINTS                 1036
#define IDC_EDIT_STATUS1ST              1037
#define IDC_EDIT_STATUS2ND              1038
#define IDC_GENESIS_LIST                1039
#define IDC_SPIN_THICKNESS              1040
#define IDC_EDIT_THICKNESS              1041
#define IDC_AVAIL_LIST                  1042
#define IDC_TOSAVE_LIST                 1043
#define IDC_ORDER_SPIN                  1044
#define IDC_PREVIEW_BUTTON              1045
#define IDC_EDIT_FIRSTVALUE             1046
#define IDC_EDIT_FIRSTSAVEDVALUE        1046
#define IDC_COMBO_ZOOM                  1047
#define IDC_EDIT_YNAME                  1048
#define IDC_EDIT_AXENAME                1049
#define IDC_TREE_CURVES                 1060
#define IDC_PREVIEW                     1062
#define IDC_DELETE_ELEMENT              1064
#define IDC_UNDO                        1067
#define IDC_REDO                        1068
#define IDC_RESET_MODIFICATION          1069
#define IDC_BUTTON1                     1070
#define IDC_STATIC_PRODID               1073
#define IDC_STATIC_REGISTERED           1074
#define IDC_STATIC_LICENCEDNAME         1075
#define IDC_STATIC_LICENCEDCOMPNAME     1076
#define IDC_ADV_CONTINUOUS_BUTTON       1076
#define IDC_BLACKCOLOR_BUTTON           1077
#define IDC_SLIDER_RED                  1080
#define IDC_SLIDER_GREEN                1081
#define IDC_SLIDER_BLUE                 1082
#define IDC_EDIT_RED                    1083
#define IDC_EDIT_GREEN                  1084
#define IDC_EDIT_BLUE                   1085
#define IDC_CHECK_PICKCOLOR             1086
#define IDC_RADIO_FLAT_THICKNESS        1087
#define IDC_RADIO_SMART_THICKNESS       1088
#define IDC_EDIT_THICK_RANGE            1089
#define IDC_SPIN_RANGE                  1090
#define IDC_RADIO_TOOL_PEN              1091
#define IDC_RADIO_TOOL_RUBBER           1092
#define IDC_REGISTER_BUTTON             1093
#define IDC_LIST3                       1097
#define IDC_CHECK_AXE                   1098
#define IDC_RADIO2                      1104
#define IDC_STATIC_STATUS               1105
#define IDC_STATIC_PT1                  1108
#define IDC_STATIC_PT2                  1109
#define IDC_RADIO_DASHED                1110
#define IDC_RADIO_NOTDASHED             1111
#define IDC_EDIT_DISTMAX                1113
#define IDC_BUTTON_DASHDIST             1115
#define IDC_BUTTON_APPLY                1116
#define IDC_SPIN_DIST                   1118
#define IDC_EDIT_DASHDIST               1119
#define IDC_STATIC_QUESTION             1121
#define IDC_RADIO_SAVE_EXPORT           1122
#define IDC_RADIO_SAVE_DOCUMENT         1123
#define IDC_STATIC_NBOFSAVEDPOINTS      1124
#define IDC_EXPORTFORMAT_BUTTON         1125
#define IDC_RADIO_SEP_SEMICOLON         1126
#define IDC_RADIO_SEP_TAB               1127
#define IDC_RADIO_SEP_COMMA             1128
#define IDC_RADIO_SEP_SPACE             1129
#define IDC_RADIO_SEP_OTHER             1130
#define IDC_EDIT_SEP_OTHER              1131
#define IDC_BOTTOM_COLOR_BUTTON         1132
#define IDC_COLOR_SCALE_BUTTON          1133
#define IDC_DEFAULT_COLOR_SCALE_BUTTON  1134
#define IDC_DENSITOPREVIEW_BUTTON       1136
#define IDC_CHECK_DRAWSEGMENT_DENSITO   1138
#define IDC_CHECK_PICK_UP_COLOR         1141
#define IDC_CHECK_PICK_BOTTOM_COLOR     1143
#define IDC_EDIT_TOP_COLOR_VALUE        1144
#define IDC_TOP_COLOR_BUTTON            1145
#define IDC_RADIO_DENSIOMETRY           1146
#define IDC_RADIO_DISP_X                1147
#define IDC_RADIO_DISP_Y                1148
#define IDC_RADIO_DISP_BOTH             1149
#define IDC_EDIT_XFIRST                 1150
#define IDC_EDIT_YFIRST                 1151
#define IDC_NB_SAVED_POINTS             1152
#define IDC_STATIC_X                    1153
#define IDC_STATIC_Y                    1154
#define IDC_STATIC_VERSION              1156
#define IDC_STATIC_BUILD_NB             1157
#define IDC_RADIO_SPLINE_ADDFRONT       1158
#define IDC_RADIO_SPLINE_ADDBACK        1159
#define IDC_SPLINE_CLEAN_ALL            1160
#define IDC_RADIO_SPLINE_ADDMIDDLE      1161
#define IDC_RADIO_SPLINE_REMOVE         1162
#define IDC_STATIC_SPLINE_TOOL_COMMENT  1163
#define IDC_RADIO_SPLINE_MODIFY         1164
#define IDC_RADIO_SPLINE_CURVE          1164
#define IDC_MINIMIZE_BUTTON             1165
#define IDC_UNDO_SPLINE_BUTTON          1166
#define IDC_REDO_SPLINE_BUTTON          1167
#define IDC_SPLINE_SAVED_POINTS_NB_EDIT 1168
#define ID_FILE_OPENBITMAP              32771
#define ID_FILE_SAVECURVES              32772
#define ID_FILE_EXIT                    32773
#define ID_GRAPH_NEWSYSTEM              32774
#define ID_VIEW_ZOOM                    32778
#define ID_GRAPH_MODIFY                 32780
#define ID_GRAPH_NEWCONTINUOUS          32781
#define ID_GRAPH_NEWDISCRETE            32782
#define ID_GRAPH_DELETEOBJECT           32783
#define ID_GRAPH_NEW_COORDANDCURVE      32788
#define ID_TOOLS_SETTINGS               32790
#define ID_VIEW_OPTIONS                 32793
#define ID_SCANNER_SELECTSOURCE         32798
#define ID_SCANNER_IMPORT               32799
#define ID_GRAPH_NEWDENSITOCURVE        32800
#define ID_GRAPH_NEWSPLINECURVE         32802
#define ID_INDICATOR_XLABEL             59143
#define ID_INDICATOR_YLABEL             59144
#define ID_INDICATOR_XVALUE             59145
#define ID_INDICATOR_YVALUE             59146
#define IDS_NOT_PARALLEL                61204
#define IDS_FAIL_TO_OPEN_FILE           61205
#define IDS_CANNOT_HANDLE_X_COLORS      61206
#define IDS_COLOR_RANGE                 61207
#define IDS_THICK_WHIDTH_RANGE          61208
#define IDS_HAND_MODIFICATION_LOST      61209
#define IDS_NOT_ENOUGH_MEMORY           61210
#define IDS_GENESIS_POINT_REDUNDANT     61211
#define IDS_NO_POINT_SELECTED           61212
#define IDS_NO_CURVE_HERE               61213
#define IDS_OUT_OF_LIMITS               61214
#define IDS_CURVE_ALREADY_EXISTS        61215
#define IDS_RIGHT_GREATER_THAN_LEFT     61216
#define IDS_LEFT_GREATER_THAN_RIGHT     61217
#define IDS_LOG_VALUE_GREATER_THAN_ZERO 61218
#define IDS_PERIOD_GREATER_THAN_ZERO    61219
#define IDS_CURVE_CONTAINS_N_LINES      61220
#define IDS_SCALE_VALUES_DIFFERENT      61221
#define IDS_LOG_GREATER_THAN_ZERO2      61222
#define IDS_CURVES_NOT_SAVED_EXIT       61223
#define IDS_OUT_OF_MEMORY               61224
#define IDS_SELECT_COORD_SYST           61225
#define IDS_DELETE_COORD_SYST           61226
#define IDS_DIVISION_BY_ZERO            61227
#define IDS_NAME_FIELD_EMPTY            61228
#define IDS_LICENCE_KEY_EMPTY           61229
#define IDS_LICENCE_KEY_NOT_VALID       61230
#define IDS_CANNOT_OPEN_TO_WRITE        61231
#define IDS_CANNOT_WRITE_INTO_FILE      61232
#define IDS_CURVES_NOT_SAVED_OPEN       61233
#define IDS_LOG_GREATER_THAN_ZERO3      61234
#define IDS_STATE_OK                    61235
#define IDS_STATE_VALUE                 61236
#define IDS_STATE_PICK                  61237
#define IDS_DECADE_UNIT                 61238
#define IDS_PRODUCT_LICENCED            61239
#define IDS_PRODUCT_UNREGISTERED        61240
#define IDS_PRODUCTID                   61241
#define IDS_ZOOMFIT                     61242
#define IDS_NEXTBUTTON                  61243
#define IDS_FINISHBUTTON                61244
#define IDS_RESULTHEADER1               61245
#define IDS_RESULTHEADER2               61246
#define IDS_RESULTHEADER3               61247
#define IDS_PREVIEWLIMIT                61248
#define IDS_GRAPHICFILTERNAME           61249
#define IDS_GRAPHICFILTERNAME_ALL       61250
#define IDS_OUTPUTFILTERNAME            61251
#define IDS_OUTPUTFILTER                61251
#define IDS_SCALE_POINT_DIFFERENT       61252
#define IDS_AXE_PLEASE_DRAW             61253
#define IDS_X_AXIS_NAME                 61254
#define IDS_Y_AXIS_NAME                 61255
#define IDS_AXE_PICK_POINT              61256
#define IDS_AXE_ENTER_VALUE             61257
#define IDS_AXE_ENTER_VALUE_AND_POSITION 61258
#define IDS_AXE_READY                   61259
#define IDS_AXE_DEFINE_POINT            61260
#define IDS_AXE_DEFINE_SCALEPOINT       61261
#define IDS_INSTALL_NOT_CORRECT         61262
#define IDS_ADMINISTRATOR_RIGHTS        61263
#define IDS_NAME_ALREADY_EXISTS         61264
#define IDS_UNTITLED                    61265
#define IDS_CURVES_NOT_SAVED_SCANNING   61266
#define IDS_NO_SCANNER_AVAILABLE        61267
#define IDS_ERROR                       61268
#define IDS_NBLINESTOOBIG               61269
#define IDS_SEPARATOR_ISEMPTY           61270
#define IDS_SCANNED_GRAPHIC             61271
#define IDS_EXCEL_FILTER                61272
#define IDS_TEXT_FILTER                 61273
#define IDS_GENERIC_FILTER              61274
#define IDS_MUST_GIVE_VALUE             61275
#define IDS_SCALE_VALUE_MUST_BE_DIFFERENT 61276
#define IDS_SCALE_COLOR_MUST_BE_DIFFERENT 61277
#define IDS_DENSITO_PREVIEW_TITLE       61278
#define IDS_VALUE_OUTSIDE_RANGE         61279
#define IDS_SPLINE_CANNOT_ADD_NEW_ONE   61280
#define IDS_SPLINE_CANNOT_ADD_MIDDLEPOINT 61281
#define IDS_SPLINE_CANNOT_REMOVE_NODE   61282
#define IDS_SPLINE_CANNOT_MODIFY_POINT  61283
#define IDS_SPLINE_CLEANALL_CONFIRM     61284
#define IDS_SPLINE_TOOL_ADD_BACK        61285
#define IDS_SPLINE_TOOL_ADD_FRONT       61286
#define IDS_SPLINE_TOOL_ADD_MIDDLE      61287
#define IDS_SPLINE_TOOL_REMOVE          61288
#define IDS_SPLINE_TOOL_MODIFY          61289

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1169
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
